### ISSUE TITLE
Cannot read properties of undefined (reading 'borderColor')

### ISSUE THREAD

**Issue by preludeofme** [jeanverster/chakra-ui-steps#37] opened 2021-11-29 14:19 UTC
Getting the following error when using this library with Nextjs/typescript:

Cannot read properties of undefined (reading 'borderColor')

error occurs on file: chakra-ui-steps\dist\chakra-ui-steps.esm.js

![image](https://user-images.githubusercontent.com/27815916/143883540-fd2a649a-3bb6-42ec-ac68-f20fe51b0476.png)

If I add the commented code it "fixes" it for me, but that's just to get the error to go away. 

here's my package.json if that helps:

"dependencies": {
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.7",
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@fontsource/open-sans": "^4.5.1",
    "@fontsource/raleway": "^4.5.0",
    "@hookform/resolvers": "^2.8.3",
    "@prisma/client": "^3.3.0",
    "@types/next-auth": "^3.15.0",
    "axios": "^0.23.0",
    "chakra-ui-steps": "^1.5.0",
    "framer-motion": "^4.1.17",
    "next": "11.1.2",
    "next-auth": "^3.28.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-hook-form": "^7.17.4",
    "react-icons": "^4.3.1",
    "react-new-window": "^0.1.3",
    "react-query": "^3.32.3",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "17.0.27",
    "eslint": "7.32.0",
    "eslint-config-next": "11.1.2",
    "prisma": "^3.3.0",
    "typescript": "4.4.3"
  }

**Comment by c0rdeiro** [comment] 2021-12-03 15:10
can you guys hotfix this bug?

**Comment by jeanverster** [comment] 2021-12-03 15:17
Yeah I will look into this after work today 👍🏼 Sorry for the delay!

**Comment by jeanverster** [comment] 2021-12-05 07:35
Hey @preludeofme - I just tried in a fresh next project with no issues. Did you extend the chakra theme with the steps styles like in the readme?
```tsx
import { StepsStyleConfig as Steps } from 'chakra-ui-steps';

const theme = extendTheme({
  components: {
    Steps,
  },
});

export const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <YourApp />
    </ChakraProvider>
  );
};
```

**Comment by jeanverster** [comment] 2021-12-07 07:47
Closing this as I'm fairly certain it will be fixed by adding the styles config as mentioned above, let me know if it still doesn't work

**Comment by c0rdeiro** [comment] 2021-12-07 20:29
Well I had the styles added but had some others that might be confliting, I dont know.
I just downgraded the version to 1.3.0 and got it to work

**Comment by preludeofme** [comment] 2021-12-07 20:44
sorry i missed the response. yeah i had the theme added and still got the error. I'm not sure if i was missing anything else but i followed the documentation on my app.

**Comment by jeanverster** [comment] 2021-12-08 07:30
@preludeofme @c0rdeiro would it be possible for you to provide me with a sample repo / codesandbox which reproduces the error? I'm struggling to reproduce it on my side

**Comment by preludeofme** [comment] 2021-12-08 15:57
I'll put together something tonight for you

**Comment by OleksandrFomin** [comment] 2021-12-15 08:45
I managed to make it work in the following way



`
// stepper.ts

import { StepsStyleConfig as Steps } from 'chakra-ui-steps';

export const Stepper = {
    ...Steps,
    variants: {
        brand: {
            stepIconContainer: {
               //...insert styles
            },

            label: {
               //...insert styles
            },
        },
    },
};
`

`
`

**Comment by OleksandrFomin** [comment] 2021-12-15 08:48
I managed to make it work in the following way


```
// stepper.ts

import { StepsStyleConfig as Steps } from 'chakra-ui-steps';

export const Stepper = {
...Steps,
     variants: {
           brand: {
                stepIconContainer: {
                    //...insert styles
                  },

                 label: {
                    //...insert styles
                 },
        },
    },
};
```

```
//theme.ts

import { extendTheme } from '@chakra-ui/react';
import { Stepper } from './components/stepper';

const theme = extendTheme({
    components: {
        Steps: Stepper,
    },
});
```

**Comment by jeanverster** [comment] 2022-01-23 19:00
Closing this as unable to reproduce. Happy to re-open if someone can provide a codesandbox showing the issue 👍🏼

**Closed by jeanverster** 2022-01-23 19:00 UTC

**Comment by annakaz** [comment] 2022-03-06 19:06
@OleksandrFomin 's workaround worked for me as well using next js, otherwise I got the error `Cannot read properties of undefined (reading 'width')`. Maybe something finicky with the next js config

Did not work with this in components
<img width="758" alt="Screen Shot 2022-03-06 at 11 06 10 AM" src="https://user-images.githubusercontent.com/16907027/156938225-188e5a35-6019-4512-a657-8146f1c696b9.png">

Did work with this in components
<img width="635" alt="Screen Shot 2022-03-06 at 11 06 40 AM" src="https://user-images.githubusercontent.com/16907027/156938244-d1e6a7ad-ff4e-4021-8845-d5c093d14f1f.p
<img width="930" alt="Screen Shot 2022-03-06 at 11 06 50 AM" src="https://user-images.githubusercontent.com/16907027/156938250-f8cf7316-1119-4524-91cd-a53aadac1693.png">
ng">

**Comment by jeanverster** [comment] 2022-03-06 20:10
Hi @annakaz - the reason why the first screenshot did not work is because if you use the spread operator on the `Steps` variable, your `components` object would not contain a `Steps` key (which is what the theme is looking for). That also explains why the second one works, because you are adding a `Steps` key to the `components` object and assigning it to the value of `Stepper`.

It needs to look like this:
```js
components: {
    Spinner: {
        // spinner styles here
    },
    Steps: {
        // steps styles here
    }
}
```

And by using the spread operator, you are essentially doing this:
```js
components: {
    Spinner: {
        // spinner styles here
    },
    // steps styles here
}
```

The readme has been updated to show examples of how you might go about customising the different items within the stepper if you would like to update the styles :)
